-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.api_usage_logs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  user_id uuid,
  api_key_id uuid,
  user_api_key_id uuid,
  service character varying NOT NULL,
  endpoint character varying,
  method character varying,
  tokens_used integer DEFAULT 0,
  cost numeric DEFAULT 0,
  response_time integer,
  request_data jsonb,
  response_data jsonb,
  error_data jsonb,
  status character varying DEFAULT 'success'::character varying CHECK (status::text = ANY (ARRAY['success'::character varying, 'error'::character varying, 'timeout'::character varying, 'rate_limited'::character varying]::text[])),
  ip_address inet,
  user_agent text,
  CONSTRAINT api_usage_logs_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_logs_api_key_id_fkey FOREIGN KEY (api_key_id) REFERENCES public.company_api_keys(id),
  CONSTRAINT api_usage_logs_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT api_usage_logs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id),
  CONSTRAINT api_usage_logs_user_api_key_id_fkey FOREIGN KEY (user_api_key_id) REFERENCES public.user_api_keys(id)
);
CREATE TABLE public.billing_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  billing_period_start date NOT NULL,
  billing_period_end date NOT NULL,
  base_cost numeric DEFAULT 0,
  api_costs numeric DEFAULT 0,
  llm_costs numeric DEFAULT 0,
  premium_features_cost numeric DEFAULT 0,
  total_cost numeric NOT NULL,
  total_api_calls integer DEFAULT 0,
  total_llm_tokens integer DEFAULT 0,
  total_users integer DEFAULT 0,
  invoice_id character varying,
  payment_status character varying DEFAULT 'pending'::character varying,
  paid_at timestamp with time zone,
  cost_breakdown jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT billing_history_pkey PRIMARY KEY (id),
  CONSTRAINT billing_history_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.chatbot_analytics (
  id bigint NOT NULL DEFAULT nextval('chatbot_analytics_id_seq'::regclass),
  wa_id text NOT NULL,
  company_id uuid NOT NULL,
  message_id text NOT NULL,
  intent text,
  flow_executed text,
  response_type text,
  response_sent boolean,
  processing_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chatbot_analytics_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_analytics_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT chatbot_analytics_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT chatbot_analytics_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT chatbot_analytics_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(wa_id)
);
CREATE TABLE public.chatbot_contacts (
  wa_id text NOT NULL,
  company_id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  last_seen_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chatbot_contacts_pkey PRIMARY KEY (wa_id, company_id),
  CONSTRAINT chatbot_contacts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.chatbot_messages (
  id bigint NOT NULL DEFAULT nextval('chatbot_messages_id_seq'::regclass),
  wa_id text NOT NULL,
  company_id uuid NOT NULL,
  message_id text NOT NULL UNIQUE,
  conversation_id text,
  direction text NOT NULL CHECK (direction = ANY (ARRAY['inbound'::text, 'outbound'::text])),
  message_type text NOT NULL CHECK (message_type = ANY (ARRAY['text'::text, 'image'::text, 'audio'::text, 'video'::text, 'document'::text, 'location'::text, 'contact'::text, 'interactive'::text, 'template'::text, 'reaction'::text, 'system'::text])),
  content jsonb NOT NULL,
  raw_message jsonb,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'sent'::text, 'delivered'::text, 'read'::text, 'failed'::text])),
  message_timestamp timestamp with time zone NOT NULL,
  processed_at timestamp with time zone DEFAULT now(),
  is_automated boolean DEFAULT false,
  context_data jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chatbot_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_messages_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT chatbot_messages_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT chatbot_messages_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT chatbot_messages_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(wa_id)
);
CREATE TABLE public.chatbot_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wa_id text NOT NULL,
  company_id uuid NOT NULL,
  session_id text NOT NULL,
  current_flow text,
  session_data jsonb DEFAULT '{}'::jsonb,
  is_active boolean DEFAULT true,
  started_at timestamp with time zone DEFAULT now(),
  last_activity timestamp with time zone DEFAULT now(),
  ended_at timestamp with time zone,
  CONSTRAINT chatbot_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chatbot_sessions_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT chatbot_sessions_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT chatbot_sessions_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT chatbot_sessions_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(company_id)
);
CREATE TABLE public.client_templates (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL UNIQUE,
  description text,
  category character varying DEFAULT 'standard'::character varying,
  dashboard_config jsonb DEFAULT '{}'::jsonb,
  workspace_config jsonb DEFAULT '{}'::jsonb,
  available_features ARRAY DEFAULT ARRAY['crm'::text, 'analytics'::text, 'automation'::text],
  default_permissions jsonb DEFAULT '{}'::jsonb,
  max_users integer DEFAULT 5,
  max_contacts integer DEFAULT 1000,
  max_api_calls integer DEFAULT 10000,
  monthly_price numeric DEFAULT 0,
  setup_fee numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  created_by uuid,
  CONSTRAINT client_templates_pkey PRIMARY KEY (id),
  CONSTRAINT client_templates_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.super_admins(id)
);
CREATE TABLE public.clients (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  email text,
  phone text,
  address text,
  contact_person text,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  cuit text CHECK (validate_cuit(cuit)),
  website_url text,
  referentes jsonb CHECK (validate_referentes(referentes)),
  CONSTRAINT clients_pkey PRIMARY KEY (id),
  CONSTRAINT clients_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.companies (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL,
  slug character varying NOT NULL UNIQUE,
  domain character varying,
  logo_url text,
  contact_email character varying,
  contact_phone character varying,
  billing_address jsonb,
  template_id uuid,
  dashboard_config jsonb DEFAULT '{}'::jsonb,
  workspace_config jsonb DEFAULT '{}'::jsonb,
  custom_branding jsonb DEFAULT '{}'::jsonb,
  features ARRAY DEFAULT ARRAY['crm'::text, 'analytics'::text, 'automation'::text],
  plan character varying DEFAULT 'starter'::character varying CHECK (plan::text = ANY (ARRAY['starter'::character varying, 'professional'::character varying, 'enterprise'::character varying, 'custom'::character varying]::text[])),
  max_users integer DEFAULT 5,
  max_contacts integer DEFAULT 1000,
  max_api_calls integer DEFAULT 10000,
  billing_cycle character varying DEFAULT 'monthly'::character varying CHECK (billing_cycle::text = ANY (ARRAY['monthly'::character varying, 'yearly'::character varying]::text[])),
  monthly_price numeric DEFAULT 0,
  setup_fee numeric DEFAULT 0,
  next_billing_date date,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'suspended'::character varying, 'cancelled'::character varying, 'trial'::character varying]::text[])),
  trial_ends_at timestamp with time zone,
  timezone character varying DEFAULT 'UTC'::character varying,
  locale character varying DEFAULT 'es-ES'::character varying,
  created_by uuid,
  assigned_to uuid,
  CONSTRAINT companies_pkey PRIMARY KEY (id),
  CONSTRAINT companies_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.super_admins(id),
  CONSTRAINT companies_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.super_admins(id),
  CONSTRAINT companies_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.client_templates(id)
);
CREATE TABLE public.company_api_keys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  created_by uuid,
  service character varying NOT NULL,
  key_name character varying NOT NULL,
  encrypted_key text NOT NULL,
  config jsonb DEFAULT '{}'::jsonb,
  endpoints ARRAY,
  rate_limits jsonb DEFAULT '{}'::jsonb,
  total_calls integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  last_used timestamp with time zone,
  monthly_limit_calls integer,
  monthly_limit_cost numeric,
  daily_limit_calls integer,
  daily_limit_cost numeric,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying, 'expired'::character varying]::text[])),
  expires_at timestamp with time zone,
  CONSTRAINT company_api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT company_api_keys_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT company_api_keys_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.company_dashboard_layouts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  company_id uuid NOT NULL,
  layout_name character varying DEFAULT 'default'::character varying,
  components jsonb NOT NULL,
  grid_layout jsonb DEFAULT '{}'::jsonb,
  allowed_roles ARRAY DEFAULT ARRAY['owner'::text, 'admin'::text, 'manager'::text, 'member'::text],
  is_default boolean DEFAULT false,
  is_active boolean DEFAULT true,
  CONSTRAINT company_dashboard_layouts_pkey PRIMARY KEY (id),
  CONSTRAINT company_dashboard_layouts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.contact_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  name character varying NOT NULL,
  email character varying NOT NULL,
  company character varying NOT NULL,
  website character varying,
  pain_point text NOT NULL,
  phone character varying,
  source character varying DEFAULT 'website_form'::character varying,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'contacted'::character varying, 'qualified'::character varying, 'converted'::character varying, 'lost'::character varying]::text[])),
  lead_score integer DEFAULT 0,
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  user_agent text,
  referrer text,
  page_url text,
  ip_address inet,
  utm_source character varying,
  utm_medium character varying,
  utm_campaign character varying,
  utm_content character varying,
  utm_term character varying,
  assigned_to uuid,
  notes text,
  last_contacted_at timestamp with time zone,
  next_follow_up_at timestamp with time zone,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_leads_pkey PRIMARY KEY (id),
  CONSTRAINT contact_leads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT contact_leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.cost_alerts (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  company_id uuid,
  user_id uuid,
  alert_type character varying NOT NULL,
  threshold_amount numeric,
  threshold_percentage integer,
  notify_email boolean DEFAULT true,
  notify_slack boolean DEFAULT false,
  notify_dashboard boolean DEFAULT true,
  is_active boolean DEFAULT true,
  last_triggered timestamp with time zone,
  CONSTRAINT cost_alerts_pkey PRIMARY KEY (id),
  CONSTRAINT cost_alerts_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT cost_alerts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.daily_usage_stats (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  date date NOT NULL,
  company_id uuid NOT NULL,
  user_id uuid,
  service character varying NOT NULL,
  total_calls integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  avg_response_time integer DEFAULT 0,
  error_count integer DEFAULT 0,
  CONSTRAINT daily_usage_stats_pkey PRIMARY KEY (id),
  CONSTRAINT daily_usage_stats_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT daily_usage_stats_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.dashboard_components (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  name character varying NOT NULL,
  component_key character varying NOT NULL UNIQUE,
  description text,
  category character varying,
  default_config jsonb DEFAULT '{}'::jsonb,
  required_permissions ARRAY,
  required_features ARRAY,
  is_premium boolean DEFAULT false,
  monthly_cost numeric DEFAULT 0,
  is_active boolean DEFAULT true,
  version character varying DEFAULT '1.0.0'::character varying,
  CONSTRAINT dashboard_components_pkey PRIMARY KEY (id)
);
CREATE TABLE public.message_buffer (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  wa_id text NOT NULL,
  company_id uuid NOT NULL,
  messages text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  processing boolean DEFAULT false,
  processed boolean DEFAULT false,
  CONSTRAINT message_buffer_pkey PRIMARY KEY (id),
  CONSTRAINT message_buffer_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT message_buffer_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT message_buffer_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(wa_id),
  CONSTRAINT message_buffer_wa_id_company_id_fkey FOREIGN KEY (wa_id) REFERENCES public.chatbot_contacts(company_id),
  CONSTRAINT message_buffer_wa_id_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.chatbot_contacts(company_id)
);
CREATE TABLE public.modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  route_path text NOT NULL,
  icon text,
  category text NOT NULL CHECK (category = ANY (ARRAY['Dashboard'::text, 'Workspace'::text])),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  featureId text,
  CONSTRAINT modules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.n8n_chat_histories (
  id integer NOT NULL DEFAULT nextval('n8n_chat_histories_id_seq'::regclass),
  session_id character varying NOT NULL,
  message jsonb NOT NULL,
  CONSTRAINT n8n_chat_histories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.project_documents (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  section_name text NOT NULL,
  filename text NOT NULL,
  original_filename text NOT NULL,
  file_url text NOT NULL,
  file_size bigint NOT NULL,
  mime_type text NOT NULL,
  description text,
  uploaded_by text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_documents_pkey PRIMARY KEY (id),
  CONSTRAINT project_documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_expedientes (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  expediente_number text NOT NULL,
  expediente_type text DEFAULT 'DGROC'::text,
  status text DEFAULT 'Pendiente'::text,
  submission_date date,
  approval_date date,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_expedientes_pkey PRIMARY KEY (id),
  CONSTRAINT project_expedientes_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_sections (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  name text NOT NULL,
  order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  icon text,
  is_system boolean DEFAULT false,
  CONSTRAINT project_sections_pkey PRIMARY KEY (id),
  CONSTRAINT project_sections_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.project_stages (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  description text,
  order integer NOT NULL DEFAULT 0,
  color text DEFAULT '#3B82F6'::text,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_stages_pkey PRIMARY KEY (id),
  CONSTRAINT project_stages_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.project_status_history (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  previous_stage text,
  new_stage text NOT NULL,
  changed_by uuid,
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT project_status_history_pkey PRIMARY KEY (id),
  CONSTRAINT project_status_history_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES auth.users(id),
  CONSTRAINT project_status_history_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  company_id uuid,
  name text NOT NULL,
  address text,
  surface numeric,
  architect text,
  builder text,
  status text,
  cover_image_url text,
  dgro_file_number text,
  project_type text,
  project_use text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  client_id uuid,
  start_date date,
  end_date date,
  budget numeric,
  current_stage text DEFAULT 'Planificación'::text,
  permit_status text DEFAULT 'Pendiente'::text,
  inspector_name text,
  notes text,
  domain_report_file_url text,
  domain_report_upload_date timestamp with time zone,
  domain_report_expiry_date timestamp with time zone,
  domain_report_is_valid boolean DEFAULT false,
  domain_report_notes text,
  enable_tax_management boolean DEFAULT false,
  paid_cost_rubro_a numeric DEFAULT 0,
  paid_cost_rubro_b numeric DEFAULT 0,
  paid_cost_rubro_c numeric DEFAULT 0,
  paid_total_cost numeric DEFAULT 0,
  last_cost_update timestamp with time zone,
  projected_total_cost numeric DEFAULT 0,
  barrio text,
  ciudad text,
  director_obra text,
  profesionales jsonb CHECK (validate_profesionales(profesionales)),
  project_usage text CHECK (project_usage IS NULL OR (project_usage = ANY (ARRAY['Vivienda'::text, 'Comercial'::text, 'Industrial'::text, 'Mixto'::text]))),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT projects_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id)
);
CREATE TABLE public.properties (
  id integer NOT NULL DEFAULT nextval('properties_id_seq'::regclass),
  company_id uuid NOT NULL,
  name character varying NOT NULL,
  description text,
  price numeric,
  location character varying,
  features jsonb DEFAULT '{}'::jsonb,
  image_urls jsonb DEFAULT '[]'::jsonb,
  status character varying DEFAULT 'available'::character varying CHECK (status::text = ANY (ARRAY['available'::character varying, 'sold'::character varying, 'reserved'::character varying, 'inactive'::character varying]::text[])),
  category character varying,
  tags ARRAY,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT properties_pkey PRIMARY KEY (id),
  CONSTRAINT properties_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.pyme_leads (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  company_id uuid NOT NULL,
  full_name character varying NOT NULL,
  company character varying NOT NULL,
  position character varying NOT NULL,
  email character varying NOT NULL,
  phone character varying NOT NULL,
  website character varying,
  country character varying NOT NULL,
  how_found_us text NOT NULL,
  monthly_revenue character varying NOT NULL,
  additional_info text,
  source character varying DEFAULT 'pyme_form'::character varying,
  status character varying DEFAULT 'new'::character varying CHECK (status::text = ANY (ARRAY['new'::character varying, 'contacted'::character varying, 'qualified'::character varying, 'converted'::character varying, 'lost'::character varying]::text[])),
  lead_score integer DEFAULT 0 CHECK (lead_score >= 0 AND lead_score <= 100),
  priority character varying DEFAULT 'medium'::character varying CHECK (priority::text = ANY (ARRAY['low'::character varying, 'medium'::character varying, 'high'::character varying, 'urgent'::character varying]::text[])),
  user_agent text,
  referrer text,
  page_url text,
  ip_address inet,
  utm_source character varying,
  utm_medium character varying,
  utm_campaign character varying,
  utm_content character varying,
  utm_term character varying,
  assigned_to uuid,
  notes text,
  last_contacted_at timestamp with time zone,
  next_follow_up_at timestamp with time zone,
  submitted_at timestamp with time zone DEFAULT now(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT pyme_leads_pkey PRIMARY KEY (id),
  CONSTRAINT pyme_leads_assigned_to_fkey FOREIGN KEY (assigned_to) REFERENCES public.user_profiles(id),
  CONSTRAINT pyme_leads_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id)
);
CREATE TABLE public.registration_requests (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  full_name text NOT NULL,
  email text NOT NULL,
  company_name text NOT NULL,
  phone text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'approved'::text, 'rejected'::text, 'processed'::text])),
  requested_at timestamp with time zone DEFAULT now(),
  processed_at timestamp with time zone,
  processed_by uuid,
  notes text,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT registration_requests_pkey PRIMARY KEY (id)
);
CREATE TABLE public.super_admins (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid,
  email character varying NOT NULL UNIQUE,
  full_name character varying,
  avatar_url text,
  role character varying DEFAULT 'admin'::character varying CHECK (role::text = ANY (ARRAY['super_admin'::character varying, 'admin'::character varying, 'support'::character varying]::text[])),
  permissions ARRAY DEFAULT ARRAY['manage_clients'::text, 'view_analytics'::text, 'manage_billing'::text],
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying]::text[])),
  last_login timestamp with time zone,
  CONSTRAINT super_admins_pkey PRIMARY KEY (id),
  CONSTRAINT super_admins_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.tax_payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid,
  payment_type text NOT NULL,
  reference_id uuid,
  rubro text NOT NULL,
  amount numeric NOT NULL,
  payment_date timestamp with time zone NOT NULL,
  receipt_number text,
  description text,
  notes text,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT tax_payments_pkey PRIMARY KEY (id),
  CONSTRAINT tax_payments_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT tax_payments_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.template_modules (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  template_id uuid,
  module_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT template_modules_pkey PRIMARY KEY (id),
  CONSTRAINT template_modules_module_id_fkey FOREIGN KEY (module_id) REFERENCES public.modules(id),
  CONSTRAINT template_modules_template_id_fkey FOREIGN KEY (template_id) REFERENCES public.client_templates(id)
);
CREATE TABLE public.user_api_keys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  service character varying NOT NULL,
  key_identifier character varying NOT NULL,
  encrypted_key text NOT NULL,
  total_calls integer DEFAULT 0,
  total_tokens integer DEFAULT 0,
  total_cost numeric DEFAULT 0,
  last_used timestamp with time zone,
  monthly_limit_calls integer DEFAULT 1000,
  monthly_limit_tokens integer DEFAULT 100000,
  monthly_limit_cost numeric DEFAULT 50.00,
  current_month_calls integer DEFAULT 0,
  current_month_tokens integer DEFAULT 0,
  current_month_cost numeric DEFAULT 0,
  current_month_reset date DEFAULT date_trunc('month'::text, now()),
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'suspended'::character varying, 'over_limit'::character varying]::text[])),
  CONSTRAINT user_api_keys_pkey PRIMARY KEY (id),
  CONSTRAINT user_api_keys_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT user_api_keys_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_custom_views (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  user_id uuid NOT NULL,
  company_id uuid NOT NULL,
  view_name character varying NOT NULL,
  view_type character varying NOT NULL,
  config jsonb NOT NULL,
  filters jsonb DEFAULT '{}'::jsonb,
  sorting jsonb DEFAULT '{}'::jsonb,
  is_shared boolean DEFAULT false,
  shared_with_roles ARRAY,
  CONSTRAINT user_custom_views_pkey PRIMARY KEY (id),
  CONSTRAINT user_custom_views_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT user_custom_views_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.user_profiles(id)
);
CREATE TABLE public.user_profiles (
  id uuid NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  email character varying NOT NULL,
  full_name character varying,
  avatar_url text,
  company_id uuid,
  role character varying DEFAULT 'member'::character varying,
  custom_permissions jsonb DEFAULT '{}'::jsonb,
  dashboard_config jsonb DEFAULT '{}'::jsonb,
  workspace_config jsonb DEFAULT '{}'::jsonb,
  custom_views jsonb DEFAULT '{}'::jsonb,
  api_access_enabled boolean DEFAULT false,
  api_rate_limit integer DEFAULT 100,
  monthly_llm_limit_cost numeric DEFAULT 10.00,
  monthly_api_limit_calls integer DEFAULT 1000,
  status character varying DEFAULT 'active'::character varying CHECK (status::text = ANY (ARRAY['active'::character varying, 'inactive'::character varying, 'pending'::character varying, 'suspended'::character varying]::text[])),
  last_login timestamp with time zone,
  preferences jsonb DEFAULT '{}'::jsonb,
  timezone character varying DEFAULT 'UTC'::character varying,
  locale character varying DEFAULT 'es-ES'::character varying,
  onboarding_completed boolean DEFAULT false,
  onboarding_step integer DEFAULT 0,
  CONSTRAINT user_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT user_profiles_company_id_fkey FOREIGN KEY (company_id) REFERENCES public.companies(id),
  CONSTRAINT user_profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);